export { pope } from './pope'
export { isDormant, emperor } from './emperor'
export { riposteSquares, onMarshalLine, marshal } from './marshal'
export { assassin } from './assassin'
export { sentinel } from './sentinel'
export { mage } from './mage'
export { herald } from './herald'
export { templar } from './templar'
export { legionary } from './legionary'